'use client';
import './global.css';
import { Toaster } from 'sonner';
import { BackgroundBeams } from '../components/ui/background-beams';
import { NextUIProvider } from '@nextui-org/react';
// export const metadata = {
//   title: 'Welcome to frontend',
//   description: 'Generated by create-nx-workspace',
// };
//
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative">
        <NextUIProvider>
          <Toaster />
          <BackgroundBeams>
            <div className="z-10">{children}</div>
          </BackgroundBeams>
        </NextUIProvider>
      </body>
    </html>
  );
}
