import './global.css';
import { Toaster } from 'sonner';
import { BackgroundBeamsDemo } from '../components/ui/background-beams';

export const metadata = {
  title: 'Welcome to frontend',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <BackgroundBeamsDemo />
        <Toaster />
        {children}
      </body>
    </html>
  );
}
