export const CLAWS_CONFIG = {
  ROOM_NAME: 'claws',
  MAX_PLAYERS: 8,
  MIN_PLAYERS_TO_START: 1,
  PLAYER_TURN_DURATION: 3000000,
  TIMEOUT_BEFORE_NEXT_TURN: 3000,
  ALLOW_RECONNECTION: true,
  RECONNECTION_TIMEOUT: 30000,
};
