import { ReactNode } from 'react';

import { Toaster } from 'sonner';

import './global.css';
import { Providers } from './providers';

export const metadata = {
  title: 'Welcome to claws',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <Providers>
        <Toaster />
        <body>{children}</body>
      </Providers>
    </html>
  );
}
