import { ReactNode } from 'react';

import { Toaster } from 'sonner';

import { UserInformation } from '../lib/features/auth/components/userInformation';
import './global.css';
import { Providers } from './providers';

export const metadata = {
  title: 'Welcome to claws',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Toaster />
          <UserInformation />
          {children}
        </Providers>
      </body>
    </html>
  );
}
