version: '3.7'
services:
  frontend:
    image: frontend:latest
    build:
        context: ../..
        dockerfile: apps/frontend/Dockerfile
    ports:
      - "3000:3000"

  tiktok-live-connector:
    image: tiktok-live-connector:latest
    build:
        context: ../..
        dockerfile: ../../apps/backend/tiktok-live-connector/Dockerfile
    ports:
      - "4444:4444"
