name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: apps/frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/playrooms-staging:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Send webhook to server
        run: |
          curl -X POST -H 'Content-type: application/json' --data \
          '{"channel": "#playrooms", "username": "5oStudios", "text": "Docker Build and Push GitHub Action: Success!", "icon_emoji": ":ghost:"}' \
            ${{ secrets.SLACK_WEBHOOK }}
